# Generated by Django 4.2.11 on 2024-03-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateHolder',
            fields=[
                ('nhs_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificateInfo',
            fields=[
                ('certificate_number', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_start_date', models.DateField()),
                ('certificate_duration', models.DurationField()),
                ('certificate_expiration_date', models.DateField()),
                ('certificate_active', models.BooleanField()),
                ('certificate_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matex_app.certificateholder')),
            ],
        ),
    ]
