# Generated by Django 4.2.11 on 2024-03-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateinfo',
            name='certificate_expiration_date',
            field=models.DateField(null=True),
        ),
    ]
