# Generated by Django 4.2.11 on 2024-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matex_app', '0002_alter_certificateinfo_certificate_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateinfo',
            name='certificate_start_date',
            field=models.DateField(null=True),
        ),
    ]
