# Generated by Django 4.2.11 on 2024-03-15 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matex_app', '0006_alter_certificateinfo_certificate_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateinfo',
            name='certificate_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 18, 30, 29, 626991)),
        ),
    ]
